### ISSUE TITLE
Add missing stuff to the marines vending machines

### ISSUE THREAD

**Issue by gscrvs** [Carbonhell/Aliens-Colonialmarines-WIP#12]
[Note]: # Add these items to the marines vending machine:
-The combat knife or the survival knife
-M4A3 Service Pistol and magazines for it
-Flarebox instead of flares, i sent you time ago the sprites of the box time ago.
-Add formals uniforms, normal uniforms helmets, bags, bands, radios and the marine berets.

Add these items to the combat engineer room (in the closet or the vending machine):
-C4
-A box of Thermite with a igniter

**Comment by Carbonhell** [comment]
not thermite, x4 is better

**Comment by Carbonhell** [comment]
Stuff added except uniforms etc,don't think it's needed
