### ISSUE TITLE
Apparently there's a way to get a space tile in the turbine room on the planet

### ISSUE THREAD

**Issue by Carbonhell** [Carbonhell/Aliens-Colonialmarines-WIP#19]
As title says

**Comment by gscrvs** [comment]
In the planet, there is a trubine room. Someone launched a grenade into the trubine which breached to the space.

**Comment by Carbonhell** [comment]
Fixed in https://github.com/Carbonhell/Aliens-Colonialmarines-WIP/commit/34faf29edc78e3e5ed01ee325b8a5f9d2d59f72f
