### ISSUE TITLE
More than one queen can exist apparently

### ISSUE THREAD

**Issue by Carbonhell** [Carbonhell/Aliens-Colonialmarines-WIP#20]

**Comment by gscrvs** [comment]
In a normal round of colonial marines mode, there was a queen and later a drone. The drone could evolved into queen, the result was two queens at the same time.

**Comment by Carbonhell** [comment]
Fixed in https://github.com/Carbonhell/Aliens-Colonialmarines-WIP/commit/6511f83f82efd1c135a10defd545d55211670dac
